function dedupePermissionFields(
  fields: { field: string; label: string }[],
): { field: string; label: string }[] {
  const seen = new Map<string, string>();
  fields.forEach(({ field, label }) => {
    if (!seen.has(field)) {
      seen.set(field, label);
    }
  });
  return Array.from(seen.entries()).map(([field, label]) => ({ field, label }));
}

const SYSTEM_PERMISSION_FIELDS_RAW: { field: string; label: string }[] = [
  { field: 'PermissionsApiEnabled', label: 'API Enabled' },
  { field: 'PermissionsModifyAllData', label: 'Modify All Data' },
  { field: 'PermissionsViewAllData', label: 'View All Data' },
  { field: 'PermissionsManageUsers', label: 'Manage Users' },
  { field: 'PermissionsEditReadonlyFields', label: 'Edit Read-Only Fields' },
  { field: 'PermissionsRunReports', label: 'Run Reports' },
  { field: 'PermissionsCreateCustomizeReports', label: 'Create and Customize Reports' },
  { field: 'PermissionsImportPersonal', label: 'Import Personal Contacts' },
  { field: 'PermissionsEditTask', label: 'Edit Tasks' },
  { field: 'PermissionsEditEvent', label: 'Edit Events' },
  { field: 'PermissionsExportReport', label: 'Export Reports' },
  { field: 'PermissionsManageCases', label: 'Manage Cases' },
  { field: 'PermissionsTransferAnyCase', label: 'Transfer Cases' },
  { field: 'PermissionsManageLeads', label: 'Manage Leads' },
  { field: 'PermissionsManageSolutions', label: 'Manage Solutions' },
  { field: 'PermissionsManageCssUsers', label: 'Manage Self-Service Users' },
  { field: 'PermissionsActivateContract', label: 'Activate Contracts' },
  { field: 'PermissionsActivateOrder', label: 'Activate Orders' },
  { field: 'PermissionsImportLeads', label: 'Import Leads' },
  { field: 'PermissionsManagePartners', label: 'Manage Partners' },
  { field: 'PermissionsTransferAnyLead', label: 'Transfer Leads' },
  { field: 'PermissionsViewSetup', label: 'View Setup and Configuration' },
  { field: 'PermissionsManageCategories', label: 'Manage Categories' },
  { field: 'PermissionsEditOppLineItemUnitPrice', label: 'Edit Opportunity Product Sales Price' },
  { field: 'PermissionsTransferAnyEntity', label: 'Transfer Records' },
  { field: 'PermissionsOverrideForecasts', label: 'Override Forecasts' },
  { field: 'PermissionsViewAllForecasts', label: 'View All Forecasts' },
  { field: 'PermissionsAllowUniversalSearch', label: 'Knowledge User' },
  { field: 'PermissionsSendSitRequests', label: 'Send Stay-in-Touch Updates' },
  { field: 'PermissionsManageRemoteAccess', label: 'Manage Connected Apps' },
  { field: 'PermissionsCanUseNewDashboardBuilder', label: 'Drag-and-Drop Dashboard Builder' },
  { field: 'PermissionsManageDynamicDashboards', label: 'Manage Dynamic Dashboards' },
  { field: 'PermissionsManageInteraction', label: 'Manage Flow' },
  { field: 'PermissionsViewMyTeamsDashboards', label: "View My Team's Dashboards" },
  { field: 'PermissionsModerateChatter', label: 'Moderate Chatter' },
  { field: 'PermissionsResetPasswords', label: 'Reset User Passwords and Unlock Users' },
  { field: 'PermissionsFlowUser', label: 'Run Flows' },
  { field: 'PermissionsCreateCustomizeDashboards', label: 'Create and Customize Dashboards' },
  { field: 'PermissionsCreateDashboardFolders', label: 'Create Dashboard Folders' },
  { field: 'PermissionsViewPublicDashboards', label: 'View Dashboards in Public Folders' },
  { field: 'PermissionsManageDashbdsInPubFolders', label: 'Manage Dashboards in Public Folders' },
  { field: 'PermissionsEditMyDashboards', label: 'Edit My Dashboards' },
  { field: 'PermissionsEditMyReports', label: 'Edit My Reports' },
  { field: 'PermissionsViewAllUsers', label: 'View All Users' },
  { field: 'PermissionsAllowEmailIC', label: 'Send Email' },
  { field: 'PermissionsChatterInternalUser', label: 'Chatter Internal User' },
  { field: 'PermissionsManageEncryptionKeys', label: 'Manage Encryption Keys' },
  { field: 'PermissionsCreateReportFolders', label: 'Create Report Folders' },
  { field: 'PermissionsViewPublicReports', label: 'View Reports in Public Folders' },
  { field: 'PermissionsManageReportsInPubFolders', label: 'Manage Reports in Public Folders' },
  { field: 'PermissionsUseTeamReassignWizards', label: 'Use Team Reassignment Wizards' },
  { field: 'PermissionsConvertLeads', label: 'Convert Leads' },
  { field: 'PermissionsSolutionImport', label: 'Import Solutions' },
  { field: 'PermissionsManageCallCenters', label: 'Manage Call Centers' },
  { field: 'PermissionsManageSynonyms', label: 'Manage Synonyms' },
  { field: 'PermissionsViewContent', label: 'View Content in Portals' },
  { field: 'PermissionsManageEmailClientConfig', label: 'Manage Email Client Configurations' },
  { field: 'PermissionsEnableNotifications', label: 'Send Outbound Messages' },
  { field: 'PermissionsManageDataIntegrations', label: 'Manage Data Integrations' },
  { field: 'PermissionsDistributeFromPersWksp', label: 'Create Content Deliveries' },
  { field: 'PermissionsViewDataCategories', label: 'View Data Categories in Setup' },
  { field: 'PermissionsManageDataCategories', label: 'Manage Data Categories' },
  { field: 'PermissionsAuthorApex', label: 'Author Apex' },
  { field: 'PermissionsModifyMetadata', label: 'Modify Metadata Through Metadata API' },
  { field: 'PermissionsManageCustomPermissions', label: 'Manage Custom Permissions' },
  { field: 'PermissionsManageTerritories', label: 'Manage Territories' },
  { field: 'PermissionsManagePubSub', label: 'Manage Pub/Sub' },
  { field: 'PermissionsManageUnlistedGroups', label: 'Manage Unlisted Groups' },
  { field: 'PermissionsStdAutomaticActivity', label: 'Standard Automatic Activity Capture' },
  { field: 'PermissionsInsightsAppAdmin', label: 'Manage CRM Analytics' },
  { field: 'PermissionsInsightsAppUser', label: 'Use CRM Analytics' },
  { field: 'PermissionsManageHealthCheck', label: 'Manage Health Check' },
  { field: 'PermissionsManageCertificates', label: 'Manage Certificates' },
  { field: 'PermissionsCreateReportInLightning', label: 'Create Reports in Lightning' },
  { field: 'PermissionsPreventClassicExperience', label: 'Hide Option to Switch to Salesforce Classic' },
  { field: 'PermissionsUseMySearch', label: 'Einstein Search' },
  { field: 'PermissionsLtngPromoReserved01UserPerm', label: 'Lightning Experience User' },
  { field: 'PermissionsManageSandboxes', label: 'Manage Sandboxes' },
  { field: 'PermissionsViewEventLogFiles', label: 'View Event Log Files' },
  { field: 'PermissionsManageSessionPermissionSets', label: 'Manage Session Permission Set Activations' },
  { field: 'PermissionsManageTemplatedApp', label: 'Manage Templated Apps' },
  { field: 'PermissionsUseTemplatedApp', label: 'Use Templated Apps' },
  { field: 'PermissionsSendAnnouncementEmails', label: 'Send Announcement Emails' },
  { field: 'PermissionsChatterEditOwnPost', label: 'Edit Own Posts' },
  { field: 'PermissionsCanEditPrompts', label: 'Design and Deliver In-App Guidance' },
  { field: 'PermissionsViewRoles', label: 'View Roles and Role Hierarchy' },
  { field: 'PermissionsLMOutboundMessagingUserPerm', label: 'Agent Initiated Outbound Messaging' },
  { field: 'PermissionsModifyDataClassification', label: 'Modify Data Classification' },
  { field: 'PermissionsPrivacyDataAccess', label: 'Allow user to access privacy data' },
  { field: 'PermissionsQueryAllFiles', label: 'Query All Files' },
  { field: 'PermissionsManageCMS', label: 'Manage CMS Workspaces and Channels' },
  { field: 'PermissionsSandboxTestingInCommunityApp', label: 'Test Sandboxes in Mobile Publisher for Experience Cloud' },
  { field: 'PermissionsCanApproveFeedPost', label: 'Can Approve Feed Post and Comment' },
  { field: 'PermissionsAddDirectMessageMembers', label: 'Add People to Direct Messages' },
  { field: 'PermissionsAllowViewEditConvertedLeads', label: 'View and Edit Converted Leads' },
  { field: 'PermissionsShowCompanyNameAsUserBadge', label: 'Show Company Name as Site Role' },
  { field: 'PermissionsAccessCMC', label: 'Access Experience Management' },
  { field: 'PermissionsViewMLModels', label: 'View ML Models' },
  { field: 'PermissionsNativeWebviewScrolling', label: 'Native Scrolling on Webviews' },
  { field: 'PermissionsViewRecommendations', label: 'View Recommendations' },
  { field: 'PermissionsManageTrustMeasures', label: 'Manage Trust Measures' },
  { field: 'PermissionsViewTrustMeasures', label: 'View Trust Measures' },
  { field: 'PermissionsManageLearningReporting', label: 'Manage Learning Reporting' },
  { field: 'PermissionsIsotopeCToCUser', label: 'Salesforce Anywhere Integration Access' },
  { field: 'PermissionsHasUnlimitedNBAExecutions', label: 'Unlimited Next Best Action Strategy Executions' },
  { field: 'PermissionsViewOnlyEmbeddedAppUser', label: 'Access to View-Only Licensed Templates and Apps' },
  { field: 'PermissionsAdoptionAnalyticsUser', label: 'Adoption Analytics User' },
  { field: 'PermissionsViewAllCustomSettings', label: 'View All Custom Settings' },
  { field: 'PermissionsViewAllCustomMetadata', label: 'View All Custom Metadata Types' },
  { field: 'PermissionsBranchManagementUserAccess', label: 'Branch Management User' },
  { field: 'PermissionsManageOrchInstsAndWorkItems', label: 'Manage Orchestration Runs and Work Items' },
  { field: 'PermissionsCMSECEAuthoringAccess', label: 'Salesforce CMS Experience Cloud Authoring Access' },
  { field: 'PermissionsManageC360AConnections', label: 'Manage Customer 360 Audiences Connections' },
  { field: 'PermissionsManageReleaseUpdates', label: 'Manage Release Updates' },
  { field: 'PermissionsViewAllFields', label: 'View All Fields' },
  { field: 'PermissionsSendCustomNotifications', label: 'Send Custom Notifications' },
  { field: 'PermissionsBypassMFAForUiLogins', label: 'Waive Multi-Factor Authentication for Exempt Users' },
  { field: 'PermissionsCanUpdateEmailAddress', label: 'Update Email Address' },
  { field: 'PermissionsCreateLtngTempInPub', label: 'Create Lightning Email Templates and Folders in Public Folders' },
  { field: 'PermissionsViewUserPII', label: 'View Concealed Field Data' },
  { field: 'PermissionsManageHubConnections', label: 'Manage Hub Connections' },
  { field: 'PermissionsB2BMarketingAnalyticsUser', label: 'B2B Marketing Analytics User' },
  { field: 'PermissionsTraceXdsQueries', label: 'Access Tracer for External Data Sources' },
  { field: 'PermissionsViewRestrictionAndScopingRules', label: 'View Restriction and Scoping Rules' },
  { field: 'PermissionsManageRestrictionAndScopingRules', label: 'Manage Restriction and Scoping Rules' },
  { field: 'PermissionsUseAssistantDialog', label: 'Use Einstein Assistant' },
  { field: 'PermissionsPipelineInspectorUser', label: 'Pipeline Inspection User' },
  { field: 'PermissionsViewDeveloperName', label: 'View Developer Name' },
  { field: 'PermissionsBypassEmailApproval', label: 'Bypass Email Approval' },
  { field: 'PermissionsSendEmailMessages', label: 'Send Email Messages' },
];

export const SYSTEM_PERMISSION_FIELDS = dedupePermissionFields(
  SYSTEM_PERMISSION_FIELDS_RAW,
);

export const SYSTEM_PERMISSION_LABELS = new Map(
  SYSTEM_PERMISSION_FIELDS.map(({ field, label }) => [field, label]),
);

const OBJECT_CRUD_FIELDS = [
  { field: 'PermissionsRead', label: 'Read' },
  { field: 'PermissionsCreate', label: 'Create' },
  { field: 'PermissionsEdit', label: 'Edit' },
  { field: 'PermissionsDelete', label: 'Delete' },
  { field: 'PermissionsViewAllRecords', label: 'View All' },
  { field: 'PermissionsModifyAllRecords', label: 'Modify All' },
];

export { OBJECT_CRUD_FIELDS };
